services:
  gateway:
    build: ./nginx/
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - DJANGO_SECRET=${DJANGO_SECRET}
      - ALLOWED_HOST=${ALLOWED_HOST}
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    build: ./frontend
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  media:
  static:
  pg_data: