name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: Terraform Execution
    runs-on: ubuntu-latest
    
    # Секреты Yandex Cloud передаются на уровень всей среды выполнения
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'plan' }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve
